plugins/cms/spree_dishes_management/config/routes.rb
Spree::Core::Engine.routes.draw do


  namespace :admin do
    resources :suppliers

    resources :rules do
      collection do
        put 'update_rules'
      end
    end

    resources :dish_types do
      resources :dish_type_images
      collection do
        delete 'destroy_multiple'
      end
      member do
        post 'active'
      end
      #active 'active'
      resources :products

    end
    resources :products do
      collection do
        delete 'destroy_multiple'
      end
      resources :available_ons
    end
    resources :available_ons
    resources :ingredients do
      resources :ingredient_images
      collection do
        delete 'destroy_multiple'
      end
    end

    
    resources :nutritions do
      collection do
        delete 'destroy_multiple'
      end
    end

    concern :products_ingredient_concern do
      resources :products_ingredients
    end

    resources :products, concerns: :products_ingredient_concern
    resources :ingredients, concerns: :products_ingredient_concern

    concern :product_nutrition_concern do
      resources :products_nutritions
    end

    resources :products, concerns: :product_nutrition_concern
    resources :ingredients, concerns: :product_nutrition_concern

  end

  namespace :api do
		get    "products_serve_date" => "available_ons#serve_date"
		delete "products_serve_date_delete" => "available_ons#serve_date_delete"
    post   "products_search" => "products#search"
		get   "products_get_all" => "products#get_all"
		post   "products_available_on_create" => "available_ons#create"
  end

  
  # Add your extension routes here
end

plugins/cms/spree_dishes_management/app/models/dish/dish_type_image.rb
module Dish
  class DishTypeImage < Spree::Asset
    validate :no_attachment_errors

    has_attached_file :attachment,
                      styles: { mini: '60x60>', normal: '200x200>'},
                      default_style: :dish_type,
                      url: '/spree/dish_types/:id/:style/:basename.:extension',
                      path: ':rails_root/public/spree/dish_types/:id/:style/:basename.:extension',
                      convert_options: { all: '-strip -auto-orient -colorspace sRGB' }
    validates_attachment :attachment,
      :presence => true,
      :content_type => { :content_type => %w(image/jpeg image/jpg image/png image/gif) }

    # save the w,h of the original image (from which others can be calculated)
    # we need to look at the write-queue for images which have not been saved yet
    after_post_process :find_dimensions

    def mini_url
      attachment.url(:mini, false)
    end

    def find_dimensions
      temporary = attachment.queued_for_write[:original]
      filename = temporary.path unless temporary.nil?
      filename = attachment.path if filename.blank?
      geometry = Paperclip::Geometry.from_file(filename)
      self.attachment_width  = geometry.width
      self.attachment_height = geometry.height
    end

    # if there are errors from the plugin, then add a more meaningful message
    def no_attachment_errors
      unless attachment.errors.empty?
        # uncomment this to get rid of the less-than-useful interim messages
        # errors.clear
        errors.add :attachment, "Paperclip returned errors for file '#{attachment_file_name}' - check ImageMagick installation or image source file."
        false
      end
    end
  end
end

plugins/cms/spree_dishes_management/app/controllers/spree/admin/dish_type_images_controller.rb
module Spree
  module Admin
    class DishTypeImagesController < ResourceController
       before_action :load_data

      create.before :set_viewable
      update.before :set_viewable

      def model_class
        Dish::DishTypeImage
      end

      def edit
      end

      def new
        @dish_type_image = @dish_type.images.build
      end

      private 
        def location_after_destroy
        end

        def location_after_save
          admin_dish_type_dish_type_images_url(@dish_type)
        end

        def load_data
          @dish_type = Dish::DishType.find(params[:dish_type_id])
        end

        def set_viewable
          @dish_type_image.viewable_type = 'Dish::DishType'
          @dish_type_image.viewable_id = params[:dish_type_image][:viewable_id]
        end
    end
  end
end

plugins/cms/spree_dishes_management/app/helpers/dish_type_images_helper.rb
module DishTypeImagesHelper
end

plugins/cms/spree_dishes_management/app/views/spree/admin/dish_type_images/_form.html.erb
<div data-hook="admin_image_form_fields" class="row">
  <div class="col-md-6">
    <div data-hook="file" class="form-group">
      <%= f.label :attachment, Spree.t(:filename) %>
      <%= f.file_field :attachment , name: "dish_type_image[attachment]", accept: 'image/png,image/gif,image/jpeg' %>
    </div>
    <div data-hook="variant" class="field">
      <%= f.hidden_field :viewable_id, name: "dish_type_image[viewable_id]", :value => @dish_type_image.viewable_id %><br>
    </div>
  </div>
  
</div>

plugins/cms/spree_dishes_management/app/views/spree/admin/dish_type_images/edit.html.erb
<%= render :partial => 'spree/admin/shared/dish_type_tabs', :locals => {:current =>:images}%>

<% content_for :page_title do %>
  <%= link_to Spree.t(:dish_types), admin_dish_types_url %>
  /  <%=@dish_type.name %>
<% end %>

<%= form_for [@dish_type, @dish_type_image], url: admin_dish_type_dish_type_image_url, :html => { :multipart => true } do |f| %>
  <fieldset data-hook="edit_image">
    <div data-hook="thumbnail" class="field alpha three columns align-center">
      <%= f.label Spree.t(:thumbnail) %><br>
      <%= link_to image_tag(@dish_type_image.attachment.url(:mini)), @dish_type_image.attachment.url(:dish_type) %>
    </div>
    <div class="nine columns omega">
      <%= render :partial => 'form', :locals => { :f => f } %>  
    </div>
    <div class="clear"></div>
    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'refresh' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= link_to_with_icon 'remove', Spree.t('actions.cancel'), admin_dish_type_url(@dish_type), :id => 'cancel_link', :class => 'button' %>
    </div>
  </fieldset>
<% end %>

plugins/cms/spree_dishes_management/app/views/spree/admin/dish_type_images/index.html.erb
<% content_for :page_title do %>
 <%= link_to Spree.t(:dish_types), admin_dish_types_url %>
  / <%=@dish_type.name %>
<% end %>

<%= render :partial => 'spree/admin/shared/dish_type_tabs', :locals => {:current => :images}%>
<div id="images" data-hook></div>

<% unless @dish_type.images.any? %>
    <div class="no-objects-found">
    <%= Spree.t(:no_images_found) %>.
  <% if !@dish_type.images.any? %>
    <%= button_link_to(Spree.t(:new_image), new_admin_dish_type_dish_type_image_url(@dish_type), { class: "btn-success", icon: 'add', id: 'new_image_link' }) if can? :create, Spree::Image %>
    <% end %>
  </div><!--end div no-object-found -->
<% else %>
  <table data-hook="images_table"%>
    <thead>
      <tr data-hook="images_header">
        <th colspan="2"><%= Spree.t(:thumbnail) %></th>
        <th><%= Spree.t(:alt_text) %></th>
        <th class="actions"></th>
      </tr>
    </thead>

    <tbody>
      <% (@dish_type.images).each do |image| %>
        <tr id="<%= spree_dom_id image %>" data-hook="images_row" class="<%= cycle('odd', 'even')%>">
          <td class="no-border">
          </td>
          <td class="align-center">
            <%= link_to image_tag(image.attachment.url(:mini)), image.attachment.url(:normal) %>
          </td>

          <td><%= image.alt %></td>
          <td class="actions">
            <%= link_to_with_icon 'edit', Spree.t(:edit), edit_admin_dish_type_dish_type_image_url(@dish_type, image), :no_text => true, :data => {:action => 'edit'} %>
          </td>

        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

plugins/cms/spree_dishes_management/app/views/spree/admin/dish_type_images/new.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @dish_type } %>

<% content_for :page_title do %>
  <%= link_to Spree.t(:dish_types), admin_dish_types_url %>
  /  <%=@dish_type.name %>
<% end %>

<%= form_for [ @dish_type, @dish_type_image],url: admin_dish_type_dish_type_images_url(@dish_type), html: { multipart: true } do |f| %>
  <fieldset data-hook="new_image">
  
    <%= render partial: 'form', locals: { f: f } %>

    <div class="form-actions" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'save' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), spree.admin_dish_type_dish_type_images_url(@dish_type), icon: 'delete', id: 'cancel_link' %>
    </div>
  </fieldset>
<% end %>

plugins/cms/spree_dishes_management/app/views/spree/admin/dish_type_images/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_dish_type_image_path(@dish_type_image) %> |
<%= link_to 'Back', dish_type_images_path %>