plugins/cms/spree_dishes_management/config/routes.rb
Spree::Core::Engine.routes.draw do


  namespace :admin do
    resources :suppliers

    resources :rules do
      collection do
        put 'update_rules'
      end
    end

    resources :dish_types do
      resources :dish_type_images
      collection do
        delete 'destroy_multiple'
      end
      member do
        post 'active'
      end
      #active 'active'
      resources :products

    end
    resources :products do
      collection do
        delete 'destroy_multiple'
      end
      resources :available_ons
    end
    resources :available_ons
    resources :ingredients do
      resources :ingredient_images
      collection do
        delete 'destroy_multiple'
      end
    end

    
    resources :nutritions do
      collection do
        delete 'destroy_multiple'
      end
    end

    concern :products_ingredient_concern do
      resources :products_ingredients
    end

    resources :products, concerns: :products_ingredient_concern
    resources :ingredients, concerns: :products_ingredient_concern

    concern :product_nutrition_concern do
      resources :products_nutritions
    end

    resources :products, concerns: :product_nutrition_concern
    resources :ingredients, concerns: :product_nutrition_concern

  end

  namespace :api do
		get    "products_serve_date" => "available_ons#serve_date"
		delete "products_serve_date_delete" => "available_ons#serve_date_delete"
    post   "products_search" => "products#search"
		get   "products_get_all" => "products#get_all"
		post   "products_available_on_create" => "available_ons#create"
  end

  
  # Add your extension routes here
end

plugins/cms/spree_dishes_management/app/views/spree/admin/shared/_dish_type_tabs.html.erb
<% content_for :sidebar do %>
  <ul class="nav nav-pills nav-stacked" data-hook="admin_product_tabs">
    <%= content_tag :li, class: ('active' if current == :details) do %>
      <%= link_to_with_icon 'edit', Spree.t(:details), edit_admin_dish_type_url(@dish_type) %>
    <% end if can?(:admin, Dish::DishType) %>

    <%= content_tag :li, class: ('active' if current == :images) do %>
      <%if @dish_type.images.any? %>
        <%= link_to_with_icon 'picture', Spree.t(:images), admin_dish_type_dish_type_images_url(@dish_type) %>
      <%else %>
         <%= link_to_with_icon 'picture', Spree.t(:images), new_admin_dish_type_dish_type_image_url(@dish_type) %>
      <% end %>
    <% end if can?(:admin, Dish::DishType) %>
  </ul>
<% end %>

plugins/cms/spree_dishes_management/app/views/spree/admin/shared/_ingredient_tabs.html.erb
<% content_for :sidebar do %>
  <ul class="nav nav-pills nav-stacked" data-hook="admin_product_tabs">
    <%= content_tag :li, class: ('active' if current == :details) do %>
      <%= link_to_with_icon 'edit', Spree.t(:details), edit_admin_ingredient_url(@ingredient) %>
    <% end if can?(:admin, Dish::Ingredient) %>
    <%= content_tag :li, class: ('active' if current == :images) do %>
    	<%if @ingredient.images.any? %>
	      <%= link_to_with_icon 'picture', Spree.t(:images), edit_admin_ingredient_ingredient_image_url(@ingredient,@ingredient.images.first) %>
	    <%else %>
	       <%= link_to_with_icon 'picture', Spree.t(:images), new_admin_ingredient_ingredient_image_url(@ingredient) %>
	    <% end %>
     
    <% end if can?(:admin, Dish::Ingredient) %>
  </ul>
<% end %>

plugins/cms/spree_dishes_management/app/views/spree/admin/shared/_main_menu.html.erb
<% if can? :admin, Spree::Order %>
  <ul class="nav nav-sidebar">
    <%= tab *Spree::BackendConfiguration::ORDER_TABS, icon: 'shopping-cart' %>
  </ul>
<% end %>

<% if can? :admin, Spree::Product %>
  <ul class="nav nav-sidebar">
    <%= main_menu_tree Spree.t(:products), icon: "th-large", sub_menu: "product", url: "#sidebar-product" %>
  </ul>
<% end %>

<% if Spree.user_class && can?(:admin, Spree.user_class) %>
  <ul class="nav nav-sidebar">
    <%= tab *Spree.t(:boxes),  url: admin_boxes_path, icon: 'th' %>
  </ul>
<% end %>

<% if can? :admin, Spree::Admin::ReportsController %>
  <ul class="nav nav-sidebar">
    <%= tab *Spree.t(:reports),  url: advanced_report_overview_admin_reports_path, icon: 'file'  %>
  </ul>
<% end %>

<% if can? :index, Spree::Shipment %>
  <ul class="nav nav-sidebar">
     <%= tab :shipments, label: Spree.t(:shipments), match_path: '/shipments', icon: 'plane' %>
  </ul>
<% end %> 

<% if Spree.user_class && can?(:admin, Spree.user_class) %>
  <ul class="nav nav-sidebar">
    <%= tab *Spree::BackendConfiguration::USER_TABS, url: spree.admin_users_path, icon: 'user' %>
  </ul>
<% end %>

<% if Spree.user_class && can?(:admin, Spree.user_class) %>
  <ul class="nav nav-sidebar">
    <%= tab *Spree.t(:email_subsriptions),  url: admin_email_subscriptions_path, icon: 'envelope' %>
  </ul>
<% end %>

<% if Spree.user_class && can?(:admin, Spree.user_class) %>
  <ul class="nav nav-sidebar">
    <%= tab *Spree.t(:comments),  url: admin_comments_path, icon: 'comment' %>
  </ul>
<% end %>

<% if can? :admin, current_store %>
  <ul class="nav nav-sidebar">
    <%= main_menu_tree Spree.t(:configurations), icon: "wrench", sub_menu: "configuration", url: "#sidebar-configuration" %>
  </ul>
<% end %>

plugins/cms/spree_dishes_management/app/views/spree/admin/shared/_product_tabs.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:products), admin_products_path %> /
  <%= @product.name %>
<% end %>

<% content_for :sidebar do %>
  <ul class="nav nav-pills nav-stacked" data-hook="admin_product_tabs">
    <%= content_tag :li, class: ('active' if current == :details) do %>
      <%= link_to_with_icon 'edit', Spree.t(:details), edit_admin_product_url(@product) %>
    <% end if can?(:admin, Spree::Product) %>
    <%= content_tag :li, class: ('active' if current == :images) do %>
    <%if @product.images.any? %>
      <%= link_to_with_icon 'picture', Spree.t(:images), edit_admin_product_image_url(@product,@product.images.first) %>
    <%else %>
       <%= link_to_with_icon 'picture', Spree.t(:images), new_admin_product_image_url(@product) %>
    <% end %>
    <% end if can?(:admin, Spree::Image) %>

    <%= content_tag :li, class: ('active' if current == :ingredients) do %>
      <%= link_to_with_icon 'list-alt', Spree.t(:ingredients), admin_product_products_ingredients_url(@product) %>
    <% end if can?(:admin, Dish::Ingredient) %>

    <%= content_tag :li, class: ('active' if current == :nutritions) do %>
      <%= link_to_with_icon 'list-alt', Spree.t(:nutrition), admin_product_products_nutritions_url(@product) %>
    <% end if can?(:admin, Dish::Nutrition) %>
  </ul>

<% end %>