plugins/cms/spree_dishes_management/config/routes.rb
Spree::Core::Engine.routes.draw do


  namespace :admin do
    resources :suppliers

    resources :rules do
      collection do
        put 'update_rules'
      end
    end

    resources :dish_types do
      resources :dish_type_images
      collection do
        delete 'destroy_multiple'
      end
      member do
        post 'active'
      end
      #active 'active'
      resources :products

    end
    resources :products do
      collection do
        delete 'destroy_multiple'
      end
      resources :available_ons
    end
    resources :available_ons
    resources :ingredients do
      resources :ingredient_images
      collection do
        delete 'destroy_multiple'
      end
    end

    
    resources :nutritions do
      collection do
        delete 'destroy_multiple'
      end
    end

    concern :products_ingredient_concern do
      resources :products_ingredients
    end

    resources :products, concerns: :products_ingredient_concern
    resources :ingredients, concerns: :products_ingredient_concern

    concern :product_nutrition_concern do
      resources :products_nutritions
    end

    resources :products, concerns: :product_nutrition_concern
    resources :ingredients, concerns: :product_nutrition_concern

  end

  namespace :api do
		get    "products_serve_date" => "available_ons#serve_date"
		delete "products_serve_date_delete" => "available_ons#serve_date_delete"
    post   "products_search" => "products#search"
		get   "products_get_all" => "products#get_all"
		post   "products_available_on_create" => "available_ons#create"
  end

  
  # Add your extension routes here
end

plugins/cms/spree_dishes_management/app/models/dish/nutrition.rb
module Dish
	class Nutrition < Spree::Base
		validates_presence_of :name
		has_many :products, through: :products_nutritions, :class_name => "Spree::Product"
		has_many :products_nutritions, :class_name => "Dish::ProductsNutrition"

		accepts_nested_attributes_for :products_nutritions,
             :reject_if => :all_blank,
             :allow_destroy => true
        accepts_nested_attributes_for :products
		
		def can_be_deleted?
			products_nutritions.count == 0
		end
	end
end

plugins/cms/spree_dishes_management/app/controllers/spree/admin/nutritions_controller.rb
module Spree
  module Admin
    class NutritionsController < ResourceController
      before_action :load_data, except: :index

      def model_class
        Dish::Nutrition
      end

      def show
        redirect_to action: :edit
      end

      def load_data
      end

      def location_after_save
        admin_nutritions_url
      end
      
      def destroy_multiple
        Dish::Nutrition.destroy(params[:nutritions])  
        flash[:success] = "Deleted Successfully"
        redirect_to action: :index   
      end
      
      def collection
        return @collection if @collection.present?
        params[:q] ||= {}
        params[:q][:deleted_at_null] ||= "1"

        params[:q][:s] ||= "name asc"
        @collection = super
        if params[:q].delete(:deleted_at_null) == '0'
          @collection = @collection.with_deleted
        end
        # @search needs to be defined as this is passed to search_form_for
        @search = @collection.ransack(params[:q])
        @collection = @search.result.
              page(params[:page]).
              per(params[:per_page] || Spree::Config[:admin_products_per_page])

        @collection
      end 
    end
  end
end

plugins/cms/spree_dishes_management/app/helpers/nutritions_helper.rb
module NutritionsHelper
end

plugins/cms/spree_dishes_management/app/views/spree/admin/nutritions/_form.html.erb
<div data-hook="admin_nutrition_form">
  <div class="col-md-12" data-hook="admin_nutrition_left">
    <div class = "col-md-12"  class="" data-hook="admin_inutrition_form_name">
      <%= f.field_container :name, class: ['form-group'] do %>
        <%= f.label :name, raw(Spree.t(:nutrition_name) + content_tag(:span, ' *', class: 'required')) %>
        <%= f.text_field :name,name: "nutrition[name]", class: 'form-control title' %>
        <%= f.error_message_on :name %>
      <% end %>
    </div>

    <div class = "col-md-12" class="" data-hook="admin_nutrition_form_description">
      <%= f.field_container :description, class: ['form-group'] do %>
        <%= f.label :description, raw(Spree.t(:description)) %>
        <%= f.text_area :description,name: "nutrition[description]",rows: 5, class: 'form-control title' %>
        <%= f.error_message_on :name %>
      <% end %>
    </div>

  </div>

</div> <!--- end admin_product_form_fields-->

plugins/cms/spree_dishes_management/app/views/spree/admin/nutritions/edit.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:nutritions), admin_nutritions_url %>
  / <%=@nutrition.name %>
<% end 
%>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @nutrition } %>
<%= form_for @nutrition, method: :put, :url => admin_nutrition_url(@nutrition), :html => {:id => "edit_nutrition", :multipart => true} do |f| %>
	<fieldset data-hook="edit_nutrition">
		<%= render :partial => 'form', :locals => { :f => f } %>
		<div class="form-buttons filter-actions actions col-md-12" data-hook="buttons">
	        <%= button Spree.t('actions.update'), 'ok' %>
	        <span class="or"><%= Spree.t(:or) %></span>
	        <%= link_to_with_icon 'remove', Spree.t('actions.cancel'), admin_nutritions_url, :class => 'button' %>
	    </div>
    </fieldset>
<% end %>

plugins/cms/spree_dishes_management/app/views/spree/admin/nutritions/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:nutrition) %>
<% end %>
<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_nutrition), new_admin_nutrition_url, { :class => "btn-success", :icon => 'plus', :id => 'admin_new_nutition' } %>
<% end if can?(:create, Dish::Nutrition) %>
<%= form_tag destroy_multiple_admin_nutritions_url, method: :delete do %>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th class="col-md-2"><%= button Spree.t('actions.delete'), 'delete', 'submit', {class: 'btn-danger btn-delete',data: { confirm: "Are you sure?" }} %></th>
      <th class="col-md-3"><%= Spree.t(:name) %></th>
      <th class="col-md-5"><%= Spree.t(:description) %></th>
      <th class="col-md-2">Tools</th>
    </tr>
  </thead>

  <tbody>
    <% @nutritions.each do |nutrition| %>
      <tr>
        <td >
          <%if nutrition.can_be_deleted? %>
            <%= check_box_tag "nutritions[]", nutrition.id %>
          <%else %>
            <%= check_box_tag "nutritions[]", nutrition.id, false, disabled: true %></td>
          <%end %>
        </td>
        <td ><%= nutrition.name %></td>
        <td ><%= truncate(nutrition.description, escape: false){ link_to "more",  edit_admin_nutrition_url(nutrition)} %></td>
        <td class="actions" data-hook="admin_products_index_row_actions">
            <%= link_to_edit nutrition, :no_text => true, :class => 'edit' if can?(:edit, nutrition) %>
            &nbsp;
            <%if nutrition.can_be_deleted? %>
            <%= link_to_delete nutrition, :no_text => true if can?(:delete, nutrition) %>
            <%else %>

            <a class="btn btn-danger btn-sm icon-link with-tip btn-delete-nutrition">
              <span class="icon icon-delete"></span> 
            </a>
            <%end %>
          </tds>
      </tr>
    <% end %>
  </tbody>
</table>

<% end %>

<script type="text/javascript">
  $(' input[type=checkbox]').click(function(){
    // code goes here
  });
  $(".btn-delete-nutrition").click(function() {
    alert("Can not delete this Nutrition! Because it is used with some product. If you want to delete it, please delete the product before!");
  });
</script>

plugins/cms/spree_dishes_management/app/views/spree/admin/nutritions/new.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:nutitions), admin_ingredients_url %>
  / New
<% end 
%>

<%= form_for @nutrition, url: admin_nutritions_url(@nutrition), method: 'POST', html: { id: "new_nutrition", multipart: true } do |f|%>
	<fieldset data-hook="new_nutition">
		<%= render :partial => 'form', :locals => { :f => f } %>
		<div class="form-actions" data-hook="buttons">
		  <%= button Spree.t('actions.create'), 'ok', 'submit', {class: 'btn-success'} %>
		  <span class="or"><%= Spree.t(:or) %></span>
		  <%= button_link_to Spree.t('actions.cancel'), admin_nutritions_url, :icon => 'remove' %>
		</div>
	</fieldset>
<% end %>

plugins/cms/spree_dishes_management/app/views/spree/admin/nutritions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @nutrition.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @nutrition.description %>
</p>

<%= link_to 'Edit', edit_nutrition_path(@nutrition) %> |
<%= link_to 'Back', nutritions_path %>