plugins/cms/spree_boxes_management/config/routes.rb
Spree::Core::Engine.routes.draw do
  
  namespace :admin do
    resources :boxes do
      member do
        post 'active'
      end
      resources :box_images
    end
    concern :box_products_concern do
      resources :box_products
    end

    resources :products, concerns: :box_products_concern
    resources :boxes, concerns: :box_products_concern
    # Add your extension routes here
  end


  namespace :api do
    post "products_search_by_dish_type_and_name" => "products#search_by_dish_type_and_name"
    post "box_product_create" => "box_products#update"
    get  "boxes_serve_date" => "box_products#serve_date"
  end
    
end

plugins/cms/spree_boxes_management/app/models/dish/box_image.rb
module Dish
  class BoxImage < Spree::Asset
    validate :no_attachment_errors

    has_attached_file :attachment,
                      styles: { mini: '200x150>', normal: '200x150>'},
                      default_style: :box,
                      url: '/spree/boxes/:id/:style/:basename.:extension',
                      path: ':rails_root/public/spree/boxes/:id/:style/:basename.:extension',
                      convert_options: { all: '-strip -auto-orient -colorspace sRGB' }
    validates_attachment :attachment,
      :presence => true,
      :content_type => { :content_type => %w(image/jpeg image/jpg image/png image/gif) }

    # save the w,h of the original image (from which others can be calculated)
    # we need to look at the write-queue for images which have not been saved yet
    after_post_process :find_dimensions

    def mini_url
      attachment.url(:mini, false)
    end

    def find_dimensions
      temporary = attachment.queued_for_write[:original]
      filename = temporary.path unless temporary.nil?
      filename = attachment.path if filename.blank?
      geometry = Paperclip::Geometry.from_file(filename)
      self.attachment_width  = geometry.width
      self.attachment_height = geometry.height
    end

    # if there are errors from the plugin, then add a more meaningful message
    def no_attachment_errors
      unless attachment.errors.empty?
        # uncomment this to get rid of the less-than-useful interim messages
        # errors.clear
        errors.add :attachment, "Paperclip returned errors for file '#{attachment_file_name}' - check ImageMagick installation or image source file."
        false
      end
    end
  end
end

plugins/cms/spree_boxes_management/app/controllers/spree/admin/box_images_controller.rb
module Spree
  module Admin
    class BoxImagesController < ResourceController
       before_action :load_data

      create.before :set_viewable
      update.before :set_viewable

      def model_class
        Dish::BoxImage
      end

      def show
        redirect_to action: :edit
      end

      def new
        @box_image = @box.images.build
      end

      private 
        def location_after_destroy
        end

        def location_after_save
          edit_admin_box_box_image_url(@box,@box.images.first)
        end

        def load_data
          @box = Dish::Box.find(params[:box_id])
        end

        def set_viewable
          @box_image.viewable_type = 'Dish::Box'
          @box_image.viewable_id = params[:box_image][:viewable_id]
        end
    end
  end
end

plugins/cms/spree_boxes_management/app/helpers/box_images_helper.rb
module BoxImagesHelper
end

plugins/cms/spree_boxes_management/app/views/spree/admin/box_images/_form.html.erb
<div data-hook="admin_image_form_fields" class="row">
  <div class="col-md-6">
    <div data-hook="file" class="form-group">
      <%= f.label :attachment, Spree.t(:filename) %>
      <%= f.file_field :attachment , name: "box_image[attachment]", accept: 'image/png,image/gif,image/jpeg',id: 'image_attachment' %>
    </div>
    <div data-hook="variant" class="field">
      <%= f.hidden_field :viewable_id, name: "box_image[viewable_id]", :value => @box_image.viewable_id %><br>
    </div>
  </div>
   <div data-hook="alt_text" class="col-md-12">
    <div class="form-group"class="col-md-6">
      <%= f.label :alt, Spree.t(:alt_text) %>
      <%= f.text_area :alt, name: "box_image[alt]", :rows => 4, :class => 'form-control' %>
    </div>
  </div>
</div>

plugins/cms/spree_boxes_management/app/views/spree/admin/box_images/edit.html.erb
<%= render :partial => 'spree/admin/shared/box_tabs', :locals => {:current =>:images}%>

<% content_for :page_title do %>
  <%= link_to Spree.t(:boxs), admin_boxes_url %>
  /  <%=@box.name %>
<% end %>

<%= form_for [@box, @box_image], url: admin_box_box_image_url, :html => { :multipart => true } do |f| %>
  <div data-hook="edit_image" class="panel panel-default">
    <div class="panel-heading">
      <h1 class="panel-title">
        <%= @box_image.attachment_file_name%>
      </h1>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <div data-hook="thumbnail" class="col-md-3 text-center">
          <%= f.label Spree.t(:thumbnail) %>
          <%= link_to image_tag(@box_image.attachment.url(:mini)), @box_image.attachment.url(:box) %>
        </div>
        <div class="col-md-9">
          <%= render partial: 'form', locals: { f: f } %>
        </div>

        <div class="clear"></div>
        <div class="form-buttons filter-actions actions" data-hook="buttons">
          <%= button Spree.t('actions.update'), 'refresh' %>
          <span class="or"><%= Spree.t(:or) %></span>
          <%= link_to_with_icon 'remove', Spree.t('actions.cancel'), admin_box_url(@box), :id => 'cancel_link', :class => 'button' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

plugins/cms/spree_boxes_management/app/views/spree/admin/box_images/index.html.erb
<% content_for :page_title do %>
 <%= link_to Spree.t(:boxes), admin_boxes_url %>
  / <%=@box.name %>
<% end %>

<%= render :partial => 'spree/admin/shared/box_tabs', :locals => {:current => :images}%>
<div id="images" data-hook></div>

<% unless @box.images.any? %>
    <div class="no-objects-found">
    <%= Spree.t(:no_images_found) %>.
  <% if !@box.images.any? %>
    <%= button_link_to(Spree.t(:new_image), new_admin_box_box_image_url(@box), { class: "btn-success", icon: 'add', id: 'new_image_link' }) if can? :create, Spree::Image %>
    <% end %>
  </div><!--end div no-object-found -->
<% else %>
  <table data-hook="images_table"%>
    <thead>
      <tr data-hook="images_header">
        <th colspan="2"><%= Spree.t(:thumbnail) %></th>
        <th></th>
        <th class="actions"></th>
      </tr>
    </thead>

    <tbody>
      <% (@box.images).each do |image| %>
        <tr id="<%= spree_dom_id image %>" data-hook="images_row" class="<%= cycle('odd', 'even')%>">
          <td class="no-border">
          </td>
          <td class="align-center">
            <%= link_to image_tag(image.attachment.url(:mini)), image.attachment.url(:normal) %>
          </td>

          <td></td>
          <td class="actions">
            <%= link_to_with_icon 'edit', Spree.t(:edit), edit_admin_box_box_image_url(@box, image), :no_text => true, :data => {:action => 'edit',:class =>'btn-primary'} %>
          </td>

        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

plugins/cms/spree_boxes_management/app/views/spree/admin/box_images/new.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @box } %>

<% content_for :page_title do %>
  <%= link_to Spree.t(:boxs), admin_boxes_url %>
  /  <%=@box.name %>
<% end %>

<%= form_for [ @box, @box_image],url: admin_box_box_images_url(@box), html: { multipart: true } do |f| %>

   <div data-hook="new_image" class="panel panel-default">
    <div class="panel-heading">
      <h1 class="panel-title">
        New Image
      </h1>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <div data-hook="thumbnail" class="col-md-3 text-center">
          <%= f.label Spree.t(:thumbnail) %>
            <img id="image" src="#" alt="your image" width="100px" />
        </div>
        <div class="col-md-9">
          <%= render partial: 'form', locals: { f: f } %>
        </div>
        <div class="form-actions" data-hook="buttons">
          <%= button Spree.t('actions.update'), 'save' %>
          <span class="or"><%= Spree.t(:or) %></span>
          <%= button_link_to Spree.t('actions.cancel'), spree.admin_box_box_images_url(@box), icon: 'delete', id: 'cancel_link' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

plugins/cms/spree_boxes_management/app/views/spree/admin/box_images/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_box_image_path(@box_image) %> |
<%= link_to 'Back', box_images_path %>